#!/bin/sh

rm -f /tmp/locked.png

scrot -m -z /tmp/base.png
convert /tmp/base.png -blur 0x16 /tmp/locked.png

i3lock -e -f -c 000000 -i /tmp/locked.png

sleep 5 && [ 4000 -lt "$(xssstate -i)" ] &&  pgrep -x i3lock && xset dpms force off

