#!/bin/sh

# Toggles allowing input from the touchpad device
# xinput is required for these changes to happen without reboot

# Figure out what input device is the touchpad
id=$(xinput list | grep -i touchpad | grep -Po '(?<=id=)\d+')

# List where first element is property id that we need to change if the device
# is enabled or not, the second is the current setting
prop_set=($(xinput list-props ${id} | grep -i "device enable" | grep -Po '\d+'))
let "toggle=!${prop_set[1]}"

# Do the thing
xinput set-prop ${id} ${prop_set[0]} ${toggle}

