#!/bin/sh

cd ~/Builds
git clone https://git.suckless.org/st
cd st/
wget -O /tmp/scrollback.diff https://st.suckless.org/patches/scrollback/st-scrollback-20200504-28ad288.diff
wget -O /tmp/mouse-scroll.diff https://st.suckless.org/patches/scrollback/st-scrollback-mouse-20191024-a2c479c.diff
wget -O /tmp/altscreen-fix.diff https://st.suckless.org/patches/scrollback/st-scrollback-mouse-altscreen-20191024-a2c479c.diff
git apply /tmp/scrollback.diff
git add .
git commit -m "merge scrollback patch"
git apply /tmp/mouse-scroll.diff
git add .
git commit -m "merge shift-mousescroll patch"
git apply /tmp/altscreen-fix.diff
git add .
git commit -m "merge altscreen patch"
