#!/bin/sh

cd ~/Builds
git clone https://git.suckless.org/st
cd st/
wget -O /tmp/scrollback.diff https://st.suckless.org/patches/scrollback/st-scrollback-20190331-21367a0.diff
wget -O /tmp/mouse-scroll.diff https://st.suckless.org/patches/scrollback/st-scrollback-mouse-0.8.2.diff
wget -O /tmp/altscreen-fix.diff https://st.suckless.org/patches/scrollback/st-scrollback-mouse-altscreen-20190131-e23acb9.diff
git apply /tmp/scrollback.diff
git add .
git commit -m "merge scrollback patch"
git am /tmp/mouse-scroll.diff
git apply /tmp/altscreen-fix.diff
git add .
git commit -m "merge altscreen patch"
